<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pc9-PC" name="Default test" tests="5" failures="5" timestamp="28 Feb 2015 22:13:33 GMT" time="31.664" errors="0">
  <testcase name="testCreationNewContactWithValidData" time="7.671" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [1]: ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [1]: ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="1.32" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [1]: ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [1]: ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="1.593" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [4]: ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [4]: ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="1.829" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [5]: ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [5]: ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="1.602" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [0]: ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testCreationNewContactWithValidData -->
</testsuite> <!-- Default test -->
