<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31664" started-at="2015-02-28T22:13:01Z" finished-at="2015-02-28T22:13:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31664" started-at="2015-02-28T22:13:01Z" finished-at="2015-02-28T22:13:33Z">
      <class name="com.example.tests.ContactCreationTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="setUp" is-config="true" duration-ms="16677" started-at="2015-03-01T00:13:01Z" finished-at="2015-03-01T00:13:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testCreationNewContactWithValidData(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="testCreationNewContactWithValidData" duration-ms="7671" started-at="2015-03-01T00:13:18Z" data-provider="randomValidContactGenerator" finished-at="2015-03-01T00:13:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [contactname=test1671118773, lastname=test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [1]: ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [1]: ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-280600578, lastname= test-559921970, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreationNewContactWithValidData -->
        <test-method status="FAIL" signature="testCreationNewContactWithValidData(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="testCreationNewContactWithValidData" duration-ms="1320" started-at="2015-03-01T00:13:26Z" data-provider="randomValidContactGenerator" finished-at="2015-03-01T00:13:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [contactname=, lastname=test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [1]: ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [1]: ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1671118773, lastname= test-1935422863, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= test-1602185107, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreationNewContactWithValidData -->
        <test-method status="FAIL" signature="testCreationNewContactWithValidData(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="testCreationNewContactWithValidData" duration-ms="1593" started-at="2015-03-01T00:13:27Z" data-provider="randomValidContactGenerator" finished-at="2015-03-01T00:13:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [4]: ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [4]: ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-878318455, lastname=test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-878318455, lastname= test-973814646, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreationNewContactWithValidData -->
        <test-method status="FAIL" signature="testCreationNewContactWithValidData(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="testCreationNewContactWithValidData" duration-ms="1829" started-at="2015-03-01T00:13:28Z" data-provider="randomValidContactGenerator" finished-at="2015-03-01T00:13:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [5]: ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [5]: ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-1615257103, lastname=test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-1615257103, lastname= test1691882546, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreationNewContactWithValidData -->
        <test-method status="FAIL" signature="testCreationNewContactWithValidData(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="testCreationNewContactWithValidData" duration-ms="1602" started-at="2015-03-01T00:13:30Z" data-provider="randomValidContactGenerator" finished-at="2015-03-01T00:13:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [contactname=, lastname=, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-719105063, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreationNewContactWithValidData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.ContactCreationTests@16d8735]" name="tearDown" is-config="true" duration-ms="872" started-at="2015-03-01T00:13:32Z" finished-at="2015-03-01T00:13:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.ContactCreationTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
