<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pc9-PC" name="com.example.tests.ContactCreationTests" tests="5" failures="0" timestamp="25 Feb 2015 23:37:35 GMT" time="12.854" errors="5">
  <testcase name="testCreationNewContactWithValidData" time="2.146" classname="com.example.tests.ContactCreationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [3]: ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test963182200, lastname= test-1867328919, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test963182200, lastname= test-1867328919, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [3]: ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test963182200, lastname= test-1867328919, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test963182200, lastname= test-1867328919, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="2.427" classname="com.example.tests.ContactCreationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [5]: ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-1585582741, lastname= test-383251381, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-1585582741, lastname= test-383251381, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [5]: ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-1585582741, lastname= test-383251381, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-1585582741, lastname= test-383251381, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="2.210" classname="com.example.tests.ContactCreationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [0]: ContactData [contactname=test1802447431, lastname=, adress1=test-719743106, telefoneHome=test-1225124696, telefoneMobile=test2101056265, telefoneWork=test1211825060, email1=test733943463, email2=test539665617, selectDay=null, selectMonth=null, year=null, adress2_2=test1332001285, telefoneHome2=test-1606515824] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1802447431, lastname=, adress1=test-719743106, telefoneHome=test-1225124696, telefoneMobile=test2101056265, telefoneWork=test1211825060, email1=test733943463, email2=test539665617, selectDay=null, selectMonth=null, year=null, adress2_2=test1332001285, telefoneHome2=test-1606515824]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [contactname=test1802447431, lastname=, adress1=test-719743106, telefoneHome=test-1225124696, telefoneMobile=test2101056265, telefoneWork=test1211825060, email1=test733943463, email2=test539665617, selectDay=null, selectMonth=null, year=null, adress2_2=test1332001285, telefoneHome2=test-1606515824] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1802447431, lastname=, adress1=test-719743106, telefoneHome=test-1225124696, telefoneMobile=test2101056265, telefoneWork=test1211825060, email1=test733943463, email2=test539665617, selectDay=null, selectMonth=null, year=null, adress2_2=test1332001285, telefoneHome2=test-1606515824]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="2.340" classname="com.example.tests.ContactCreationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [0]: ContactData [contactname=, lastname=, adress1=test1746161051, telefoneHome=test2032308363, telefoneMobile=test-1387165820, telefoneWork=test-1361737529, email1=test-1445610655, email2=test1448395291, selectDay=null, selectMonth=null, year=null, adress2_2=test520406546, telefoneHome2=] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=, lastname=, adress1=test1746161051, telefoneHome=test2032308363, telefoneMobile=test-1387165820, telefoneWork=test-1361737529, email1=test-1445610655, email2=test1448395291, selectDay=null, selectMonth=null, year=null, adress2_2=test520406546, telefoneHome2=]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [contactname=, lastname=, adress1=test1746161051, telefoneHome=test2032308363, telefoneMobile=test-1387165820, telefoneWork=test-1361737529, email1=test-1445610655, email2=test1448395291, selectDay=null, selectMonth=null, year=null, adress2_2=test520406546, telefoneHome2=] != ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=, lastname=, adress1=test1746161051, telefoneHome=test2032308363, telefoneMobile=test-1387165820, telefoneWork=test-1361737529, email1=test-1445610655, email2=test1448395291, selectDay=null, selectMonth=null, year=null, adress2_2=test520406546, telefoneHome2=]] but found [ContactData [contactname=, lastname= , adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreationNewContactWithValidData -->
  <testcase name="testCreationNewContactWithValidData" time="3.731" classname="com.example.tests.ContactCreationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [3]: ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [3]: ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] != ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null] expected [ContactData [contactname=test1593441017, lastname= test1459457198, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]] but found [ContactData [contactname=test-365054200, lastname= test-284864517, adress1=null, telefoneHome=null, telefoneMobile=null, telefoneWork=null, email1=null, email2=null, selectDay=null, selectMonth=null, year=null, adress2_2=null, telefoneHome2=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTests.testCreationNewContactWithValidData(ContactCreationTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreationNewContactWithValidData -->
</testsuite> <!-- com.example.tests.ContactCreationTests -->
